### ISSUE TITLE
Problem with Tab key used to increase indent

### ISSUE THREAD

**Issue by robert7** [Akrog/evershort#7]
Hi
I'm using the Chrome Extension 0.3.1 in Chrome v.65 on Linux (Ubuntu).
Pressing Tab key increases the indent, but also inserts 4 spaces. So I need manuall to delete the spaces afterwards..
Shift-Tab decreases the indent - which works fine.

![image](https://user-images.githubusercontent.com/1135218/39179165-eb57265c-47b3-11e8-8e45-cc834772c7a5.png)

**Comment by Akrog** [comment]
Thanks for the report, I hadn't even noticed!

I originally tried to fix it by using the `on` method of the tinymce object, which is not directly accessible from the Extension, so I went down the rabbit hole of message passing between the contentscript, the background, and injecting javascript code in the current page...

And it turns out that there was a trivial solution, which is the one I've used to fix this.

**Comment by robert7** [comment]
Hi,
I did a retest today with Chrome 68.0.3440 and Evernote Shortcuts Extension 0.3.2.
Now Tab inserts 5 spaces (and does no "Indent") and Shift-Tab does no Unindent.

But the Tab, Shift-Tab doesn't appear in your readme, so maybe its intended behavior, I don't know. I was interested about a shortcut for the Indent and Unindent function.

![screen_20180813_02](https://user-images.githubusercontent.com/1135218/44016706-2bf2a4b0-9ed6-11e8-88db-a555a75f9eb5.png)

**Comment by Akrog** [comment]
I have just tested it and it's working for me on Chrome 67.0.3396.87 with v0.3.2.
The tab & shift tab are present in the README and in the extension's help:

```
⇄               Indent
Shift+⇄         Unindent
```
I'll update my Chrome version and try to reproduce.

**Comment by Akrog** [comment]
I have updated Chrome to version 68.0.3440.106 and the intent/unindent feature is working correctly for me with v0.3.2.
I know it sounds dumb, and maybe you have already done it, but have you tried reloading the page with Ctrl+r ?
It could also be that there is something weird going on with Evernote's website at the moment (I just had to delete a note 6 times for it to get removed) and that the extension is not robust enough to handle it...  Do other shortcuts work when editing notes?

**Comment by robert7** [comment]
I retested now, and now it seems to work correctly. Maybe restart of Chrome was needed or something like that. Thanks.

**Comment by Akrog** [comment]
Glad it works now  :-)
